-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:5511dc5c1e7292060d47a2423cb5bf48:9c226c392424c771fbc937a5fdbb4e30:7e82580c7ebbc2f2260750da94d0c682$
-- 

return {
	texture = 'enemyEyes.png',
	frames = {
			{
				name = "Untitled-3.png",
				spriteColorRect = { x = 2, y = 3, width = 36, height = 49 },
				uvRect = { u0 = 0.793522, v0 = 0.0454545, u1 = 0.991903, v1 = 0.863636 },
				spriteSourceSize = { width = 40, height = 59 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "horizontaleye1.png",
				spriteColorRect = { x = 0, y = 2, width = 40, height = 28 },
				uvRect = { u0 = 0.259109, v0 = 0.0454545, u1 = 0.37247, v1 = 0.954545 },
				spriteSourceSize = { width = 40, height = 30 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "horizontaleye2.png",
				spriteColorRect = { x = 0, y = 1, width = 40, height = 28 },
				uvRect = { u0 = 0.137652, v0 = 0.0454545, u1 = 0.251012, v1 = 0.954545 },
				spriteSourceSize = { width = 40, height = 30 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "horizontaleye3.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 30 },
				uvRect = { u0 = 0.00809717, v0 = 0.0454545, u1 = 0.129555, v1 = 0.954545 },
				spriteSourceSize = { width = 40, height = 30 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "verticaleye1.png",
				spriteColorRect = { x = 2, y = 4, width = 36, height = 49 },
				uvRect = { u0 = 0.587045, v0 = 0.0454545, u1 = 0.785425, v1 = 0.863636 },
				spriteSourceSize = { width = 40, height = 59 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "verticaleye2.png",
				spriteColorRect = { x = 1, y = 3, width = 36, height = 49 },
				uvRect = { u0 = 0.380567, v0 = 0.0454545, u1 = 0.578947, v1 = 0.863636 },
				spriteSourceSize = { width = 40, height = 59 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

