-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:4d211e65024f88f8cc81a01a32d8b8d4:b4dd42a79a9b3f020e144bd1fbb4d46c:a1e18896df1857f145bcb9615f5ee1f2$
-- 

return {
	texture = 'enemies.png',
	frames = {
			{
				name = "blue_100.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 60 },
				uvRect = { u0 = 0.0078125, v0 = 0.734375, u1 = 0.320312, v1 = 0.96875 },
				spriteSourceSize = { width = 80, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "blue_25.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 60 },
				uvRect = { u0 = 0.648438, v0 = 0.0078125, u1 = 0.960938, v1 = 0.242188 },
				spriteSourceSize = { width = 80, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "blue_50.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 60 },
				uvRect = { u0 = 0.328125, v0 = 0.25, u1 = 0.640625, v1 = 0.484375 },
				spriteSourceSize = { width = 80, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "blue_75.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 60 },
				uvRect = { u0 = 0.0078125, v0 = 0.492188, u1 = 0.320312, v1 = 0.726562 },
				spriteSourceSize = { width = 80, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "enemy3.png",
				spriteColorRect = { x = 0, y = 2, width = 80, height = 58 },
				uvRect = { u0 = 0.328125, v0 = 0.492188, u1 = 0.640625, v1 = 0.71875 },
				spriteSourceSize = { width = 80, height = 60 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "green_100.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 53 },
				uvRect = { u0 = 0.328125, v0 = 0.726562, u1 = 0.617188, v1 = 0.933594 },
				spriteSourceSize = { width = 74, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "green_25.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 53 },
				uvRect = { u0 = 0.328125, v0 = 0.726562, u1 = 0.617188, v1 = 0.933594 },
				spriteSourceSize = { width = 74, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "green_50.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 53 },
				uvRect = { u0 = 0.328125, v0 = 0.726562, u1 = 0.617188, v1 = 0.933594 },
				spriteSourceSize = { width = 74, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "green_75.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 53 },
				uvRect = { u0 = 0.328125, v0 = 0.726562, u1 = 0.617188, v1 = 0.933594 },
				spriteSourceSize = { width = 74, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "horizontaleye1.png",
				spriteColorRect = { x = 0, y = 2, width = 40, height = 28 },
				uvRect = { u0 = 0.847656, v0 = 0.683594, u1 = 0.957031, v1 = 0.839844 },
				spriteSourceSize = { width = 40, height = 30 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "horizontaleye2.png",
				spriteColorRect = { x = 0, y = 1, width = 40, height = 28 },
				uvRect = { u0 = 0.625, v0 = 0.828125, u1 = 0.78125, v1 = 0.9375 },
				spriteSourceSize = { width = 40, height = 30 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "horizontaleye3.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 30 },
				uvRect = { u0 = 0.789062, v0 = 0.847656, u1 = 0.945312, v1 = 0.964844 },
				spriteSourceSize = { width = 40, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red_100.png",
				spriteColorRect = { x = 1, y = 2, width = 78, height = 58 },
				uvRect = { u0 = 0.648438, v0 = 0.25, u1 = 0.953125, v1 = 0.476562 },
				spriteSourceSize = { width = 80, height = 60 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "red_25.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 60 },
				uvRect = { u0 = 0.328125, v0 = 0.0078125, u1 = 0.640625, v1 = 0.242188 },
				spriteSourceSize = { width = 80, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red_50.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 60 },
				uvRect = { u0 = 0.0078125, v0 = 0.25, u1 = 0.320312, v1 = 0.484375 },
				spriteSourceSize = { width = 80, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red_75.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 60 },
				uvRect = { u0 = 0.0078125, v0 = 0.0078125, u1 = 0.320312, v1 = 0.242188 },
				spriteSourceSize = { width = 80, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "verticaleye1.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 49 },
				uvRect = { u0 = 0.796875, v0 = 0.484375, u1 = 0.9375, v1 = 0.675781 },
				spriteSourceSize = { width = 36, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "verticaleye2.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 49 },
				uvRect = { u0 = 0.648438, v0 = 0.683594, u1 = 0.839844, v1 = 0.820312 },
				spriteSourceSize = { width = 35, height = 49 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "verticaleye3.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 49 },
				uvRect = { u0 = 0.648438, v0 = 0.484375, u1 = 0.789062, v1 = 0.675781 },
				spriteSourceSize = { width = 36, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

