-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:967aa5f24b14e4e6643f483ace9e1abd:d2d8972be676bab300e5d2cf125d980e:1479a625ec0a740505e34607e9845869$
-- 

return {
	texture = 'pickups.png',
	frames = {
			{
				name = "health.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.03125, v0 = 0.578125, u1 = 0.5, v1 = 0.8125 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "key.png",
				spriteColorRect = { x = 0, y = 0, width = 33, height = 70 },
				uvRect = { u0 = 0.03125, v0 = 0.015625, u1 = 0.546875, v1 = 0.5625 },
				spriteSourceSize = { width = 33, height = 70 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "points.png",
				spriteColorRect = { x = 1, y = 3, width = 23, height = 17 },
				uvRect = { u0 = 0.578125, v0 = 0.015625, u1 = 0.9375, v1 = 0.148438 },
				spriteSourceSize = { width = 25, height = 23 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

