-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:1e56cf221ec369b2211efbf02973c5d3:6119adcd99c55e0ea36fdc38723f4ad3:b2f580ea7c37465eac371f095cbaf8c7$
-- 

return {
	texture = 'player.png',
	frames = {
			{
				name = "crown.png",
				spriteColorRect = { x = 2, y = 1, width = 64, height = 62 },
				uvRect = { u0 = 0.703125, v0 = 0.28125, u1 = 0.953125, v1 = 0.523438 },
				spriteSourceSize = { width = 70, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "playerbody.png",
				spriteColorRect = { x = 1, y = 0, width = 98, height = 67 },
				uvRect = { u0 = 0.0078125, v0 = 0.28125, u1 = 0.269531, v1 = 0.664062 },
				spriteSourceSize = { width = 100, height = 67 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "playerbody1.png",
				spriteColorRect = { x = 1, y = 0, width = 98, height = 67 },
				uvRect = { u0 = 0.398438, v0 = 0.0078125, u1 = 0.78125, v1 = 0.269531 },
				spriteSourceSize = { width = 100, height = 67 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "playerbody2.png",
				spriteColorRect = { x = 1, y = 0, width = 98, height = 67 },
				uvRect = { u0 = 0.0078125, v0 = 0.0078125, u1 = 0.390625, v1 = 0.269531 },
				spriteSourceSize = { width = 100, height = 67 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sad1.png",
				spriteColorRect = { x = 2, y = 1, width = 66, height = 35 },
				uvRect = { u0 = 0.4375, v0 = 0.277344, u1 = 0.695312, v1 = 0.414062 },
				spriteSourceSize = { width = 70, height = 43 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sad2.png",
				spriteColorRect = { x = 3, y = 7, width = 66, height = 39 },
				uvRect = { u0 = 0.277344, v0 = 0.28125, u1 = 0.429688, v1 = 0.539062 },
				spriteSourceSize = { width = 70, height = 55 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "smile1.png",
				spriteColorRect = { x = 4, y = 5, width = 66, height = 44 },
				uvRect = { u0 = 0.191406, v0 = 0.671875, u1 = 0.363281, v1 = 0.929688 },
				spriteSourceSize = { width = 70, height = 50 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "smile2.png",
				spriteColorRect = { x = 1, y = 2, width = 68, height = 45 },
				uvRect = { u0 = 0.0078125, v0 = 0.671875, u1 = 0.183594, v1 = 0.9375 },
				spriteSourceSize = { width = 70, height = 51 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "smile3.png",
				spriteColorRect = { x = 1, y = 1, width = 68, height = 50 },
				uvRect = { u0 = 0.789062, v0 = 0.0078125, u1 = 0.984375, v1 = 0.273438 },
				spriteSourceSize = { width = 70, height = 52 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "smile4.png",
				spriteColorRect = { x = 3, y = 10, width = 64, height = 42 },
				uvRect = { u0 = 0.4375, v0 = 0.421875, u1 = 0.6875, v1 = 0.585938 },
				spriteSourceSize = { width = 70, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

