-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:bfee3f615309ad5f87e56b421f40604c:7168e41865c96e8399c30d65f3b5384d:501be954c71a057571ba81b7e0fe5685$
-- 

return {
	texture = 'playerMouths.png',
	frames = {
			{
				name = "sad1.png",
				spriteColorRect = { x = 2, y = 1, width = 66, height = 35 },
				uvRect = { u0 = 0.834951, v0 = 0.037037, u1 = 0.995146, v1 = 0.685185 },
				spriteSourceSize = { width = 70, height = 43 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sad2.png",
				spriteColorRect = { x = 3, y = 7, width = 66, height = 39 },
				uvRect = { u0 = 0.669903, v0 = 0.037037, u1 = 0.830097, v1 = 0.759259 },
				spriteSourceSize = { width = 70, height = 55 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smile1.png",
				spriteColorRect = { x = 4, y = 5, width = 66, height = 44 },
				uvRect = { u0 = 0.34466, v0 = 0.037037, u1 = 0.504854, v1 = 0.851852 },
				spriteSourceSize = { width = 70, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smile2.png",
				spriteColorRect = { x = 1, y = 2, width = 68, height = 45 },
				uvRect = { u0 = 0.174757, v0 = 0.037037, u1 = 0.339806, v1 = 0.87037 },
				spriteSourceSize = { width = 70, height = 51 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smile3.png",
				spriteColorRect = { x = 1, y = 1, width = 68, height = 50 },
				uvRect = { u0 = 0.00485437, v0 = 0.037037, u1 = 0.169903, v1 = 0.962963 },
				spriteSourceSize = { width = 70, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "smile4.png",
				spriteColorRect = { x = 3, y = 10, width = 64, height = 42 },
				uvRect = { u0 = 0.509709, v0 = 0.037037, u1 = 0.665049, v1 = 0.814815 },
				spriteSourceSize = { width = 70, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

