-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:cf9e9c622f3beae3cb2b477e6047327e:87ba9d1d4b9eebe7b79ac14286c58cc3:1744fc2dd8aa8a1cf52ead2abe15b0aa$
-- 

return {
	texture = 'roomTiles.png',
	frames = {
			{
				name = "background.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.359375, v0 = 0.015625, u1 = 0.671875, v1 = 0.328125 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.015625, v0 = 0.359375, u1 = 0.328125, v1 = 0.671875 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile3.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.015625, v0 = 0.015625, u1 = 0.328125, v1 = 0.328125 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

