-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:3e9ce8ebd675c42496e7ebd54de4c0dc:5d18b68cc0f29e5035ddf83552a68eab:1744fc2dd8aa8a1cf52ead2abe15b0aa$
-- 

return {
	texture = 'roomTiles.png',
	frames = {
			{
				name = "background.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.015625, v0 = 0.523438, u1 = 0.328125, v1 = 0.679688 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "diamond1.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.359375, v0 = 0.351562, u1 = 0.671875, v1 = 0.507812 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sky.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.015625, v0 = 0.351562, u1 = 0.328125, v1 = 0.507812 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sky2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.359375, v0 = 0.179688, u1 = 0.671875, v1 = 0.335938 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile2.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.015625, v0 = 0.179688, u1 = 0.328125, v1 = 0.335938 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tile3.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.359375, v0 = 0.0078125, u1 = 0.671875, v1 = 0.164062 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wall.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
				uvRect = { u0 = 0.015625, v0 = 0.0078125, u1 = 0.328125, v1 = 0.164062 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

